version: '3.1'

services:
  tasmota-exporter:
    image: tasmota-exporter:latest
    restart: always
    container_name: tasmota-exporter
    ports:
      - 8001:8001
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
